CREATE TABLE CONSOLA(
CONSOLE_ID int NOT NULL,
NAME CHAR(20) NULL,
CONSTRAINT CONSOLE_PK PRIMARY KEY (CONSOLE_ID)
);


CREATE TABLE VIDEOGAME(
VIDEOGAME_ID int NOT NULL,
NAME varchar(50) NULL,
PRICE NUMERIC(8,2) NULL,
IS_DISCOUNT boolean NULL,
TOTALSOLD INT NULL,
CONSOLE_ID INT NULL,
CONSTRAINT VIDEOGAME_PK PRIMARY KEY (VIDEOGAME_ID),
CONSTRAINT CONSOLE_FK
      FOREIGN KEY(CONSOLE_ID)
        REFERENCES CONSOLA(CONSOLE_ID),
);

CREATE TABLE REVIEWS(
REVIEWS_ID int NOT NULL,
REVIEW CHAR(100) NULL,
SCORE INT NULL,
VIDEOGAME_ID INT NULL,
CONSTRAINT REVIEWS_PK PRIMARY KEY (REVIEWS_ID),
constraint videogame_fk
	FOREIGN KEY(VIDEOGAME_ID)
        REFERENCES videogame(videogame_id)
);





